import json

pets = [
    # ---------------- DOGS (20) ----------------
    dict(id="labrador-retriever", species="dog", name="Labrador Retriever", size="large",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=True,
         trainability=5, groomingNeeds=2, sheddingLevel=4, hypoallergenic=False, noiseLevel=2,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[10, 12], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hip dysplasia", "obesity", "ear infections"],
         likesToDo=["fetch", "swimming", "running", "family activities"],
         personalitySummary="Friendly, outgoing, and eager to please, with a steady temperament that makes it one of the most reliable family dogs.",
         requirementsSummary="Needs daily vigorous exercise and mental stimulation; prone to weight gain so diet needs monitoring; regular vet checkups for joints."),
    dict(id="golden-retriever", species="dog", name="Golden Retriever", size="large",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=True,
         trainability=5, groomingNeeds=3, sheddingLevel=4, hypoallergenic=False, noiseLevel=2,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[10, 12], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hip dysplasia", "cancer", "heart conditions"],
         likesToDo=["fetch", "swimming", "hiking", "cuddling"],
         personalitySummary="Gentle, affectionate, and endlessly patient, a classic people-pleaser that bonds closely with the whole household.",
         requirementsSummary="Needs an active routine and weekly brushing to manage a thick double coat; benefits from early obedience training."),
    dict(id="german-shepherd", species="dog", name="German Shepherd", size="large",
         energyLevel=5, exerciseNeedsMinutesPerDay=90, goodWithKids=True, goodWithOtherPets=False,
         trainability=5, groomingNeeds=3, sheddingLevel=4, hypoallergenic=False, noiseLevel=3,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="intermediate",
         lifespanYears=[9, 13], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hip and elbow dysplasia", "bloat", "degenerative myelopathy"],
         likesToDo=["training", "hiking", "protection work", "puzzle toys"],
         personalitySummary="Confident, intelligent, and loyal, with a strong protective streak toward its family.",
         requirementsSummary="Needs a job to do — structured training and vigorous daily exercise — or it can become anxious or destructive."),
    dict(id="french-bulldog", species="dog", name="French Bulldog", size="small",
         energyLevel=2, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[10, 12], typicalCostTier="high", climatePreference="temperate",
         commonHealthIssues=["brachycephalic airway syndrome", "spinal disorders", "heat sensitivity"],
         likesToDo=["short walks", "napping", "people-watching", "indoor play"],
         personalitySummary="Playful, affectionate, and easygoing, a low-key companion that's happiest close to its people.",
         requirementsSummary="Struggles in heat and humidity due to a short snout; needs climate-controlled environments and modest exercise; often has higher vet costs."),
    dict(id="standard-poodle", species="dog", name="Poodle (Standard)", size="large",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=True,
         trainability=5, groomingNeeds=5, sheddingLevel=1, hypoallergenic=True, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="intermediate",
         lifespanYears=[10, 13], typicalCostTier="high", climatePreference="any",
         commonHealthIssues=["hip dysplasia", "bloat", "Addison's disease"],
         likesToDo=["swimming", "agility", "trick training", "fetch"],
         personalitySummary="Exceptionally smart and athletic, often more sensitive and eager to bond than its elegant looks suggest.",
         requirementsSummary="Coat needs professional grooming every 4-6 weeks; needs mental stimulation as much as physical exercise."),
    dict(id="beagle", species="dog", name="Beagle", size="medium",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=1, sheddingLevel=3, hypoallergenic=False, noiseLevel=5,
         goodForApartment=False, toleratesAloneTimeHours=3, experienceLevelNeeded="beginner",
         lifespanYears=[10, 15], typicalCostTier="low", climatePreference="any",
         commonHealthIssues=["obesity", "ear infections", "hypothyroidism"],
         likesToDo=["scent tracking", "exploring", "sniffing walks", "playing with other dogs"],
         personalitySummary="Curious, friendly, and nose-driven, a merry pack dog that gets along with almost everyone.",
         requirementsSummary="Prone to following scents and wandering off leash; a securely fenced yard and consistent recall training help a lot; famously vocal."),
    dict(id="dachshund", species="dog", name="Dachshund", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=4,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[12, 16], typicalCostTier="low", climatePreference="any",
         commonHealthIssues=["intervertebral disc disease", "obesity", "dental disease"],
         likesToDo=["digging", "short walks", "burrowing in blankets", "chasing toys"],
         personalitySummary="Bold, clever, and stubborn in equal measure, with a big personality in a small body.",
         requirementsSummary="Long spine is prone to injury — avoid stairs/jumping and keep weight in check; benefits from consistent, patient training."),
    dict(id="yorkshire-terrier", species="dog", name="Yorkshire Terrier", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=False, goodWithOtherPets=True,
         trainability=3, groomingNeeds=5, sheddingLevel=1, hypoallergenic=True, noiseLevel=4,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[11, 15], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["dental disease", "luxating patella", "tracheal collapse"],
         likesToDo=["short walks", "lap time", "toy play", "being carried along on errands"],
         personalitySummary="Feisty, affectionate, and surprisingly bold, forming intense bonds with its owner.",
         requirementsSummary="Silky coat needs daily brushing or a short trim; small size makes it fragile around very young children."),
    dict(id="boxer", species="dog", name="Boxer", size="large",
         energyLevel=5, exerciseNeedsMinutesPerDay=75, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=1, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="intermediate",
         lifespanYears=[10, 12], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["cardiomyopathy", "hip dysplasia", "cancer"],
         likesToDo=["running", "wrestling play", "fetch", "family games"],
         personalitySummary="Playful and goofy well into adulthood, with a protective, patient streak around kids.",
         requirementsSummary="High energy needs a real outlet daily; short muzzle means some heat sensitivity; benefits from early socialization."),
    dict(id="siberian-husky", species="dog", name="Siberian Husky", size="large",
         energyLevel=5, exerciseNeedsMinutesPerDay=90, goodWithKids=True, goodWithOtherPets=False,
         trainability=2, groomingNeeds=3, sheddingLevel=5, hypoallergenic=False, noiseLevel=4,
         goodForApartment=False, toleratesAloneTimeHours=3, experienceLevelNeeded="experienced",
         lifespanYears=[12, 14], typicalCostTier="medium", climatePreference="cold",
         commonHealthIssues=["hip dysplasia", "eye disorders", "hypothyroidism"],
         likesToDo=["running", "pulling/sledding games", "escaping fenced yards", "howling"],
         personalitySummary="Independent, athletic, and mischievous, bred to run and think for itself.",
         requirementsSummary="Needs serious daily exercise and secure fencing (notorious escape artists); heavy seasonal shedding; not a breed that reliably comes when called off-leash."),
    dict(id="cavalier-king-charles-spaniel", species="dog", name="Cavalier King Charles Spaniel", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=40, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=3, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=3, experienceLevelNeeded="beginner",
         lifespanYears=[9, 14], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["mitral valve disease", "syringomyelia", "ear infections"],
         likesToDo=["cuddling", "gentle walks", "fetch", "following owners room to room"],
         personalitySummary="Sweet, sociable, and affectionate, happiest curled up with its favorite person.",
         requirementsSummary="Does poorly with long stretches alone; needs regular vet monitoring for heart health as it ages."),
    dict(id="shih-tzu", species="dog", name="Shih Tzu", size="small",
         energyLevel=2, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=5, sheddingLevel=1, hypoallergenic=True, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[10, 16], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["brachycephalic airway syndrome", "eye injuries", "dental disease"],
         likesToDo=["lap time", "short walks", "indoor play", "being pampered"],
         personalitySummary="Affectionate and outgoing, a companion breed through and through with a dash of stubbornness.",
         requirementsSummary="Long coat mats without daily brushing or a short 'puppy cut'; short muzzle needs cool, low-exertion conditions."),
    dict(id="border-collie", species="dog", name="Border Collie", size="medium",
         energyLevel=5, exerciseNeedsMinutesPerDay=90, goodWithKids=True, goodWithOtherPets=True,
         trainability=5, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=3,
         goodForApartment=False, toleratesAloneTimeHours=3, experienceLevelNeeded="experienced",
         lifespanYears=[12, 15], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hip dysplasia", "collie eye anomaly", "epilepsy"],
         likesToDo=["herding games", "agility", "frisbee", "puzzle toys"],
         personalitySummary="Widely considered the most trainable dog breed — brilliant, intense, and always looking for a task.",
         requirementsSummary="Needs a serious daily job (sport, herding, structured training) or it will invent its own, often destructively; not a low-key household pet."),
    dict(id="chihuahua", species="dog", name="Chihuahua", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=20, goodWithKids=False, goodWithOtherPets=False,
         trainability=3, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=5,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[14, 16], typicalCostTier="low", climatePreference="warm",
         commonHealthIssues=["dental disease", "patellar luxation", "heart murmurs"],
         likesToDo=["lap time", "short walks", "sunbathing", "guarding its favorite person"],
         personalitySummary="Bold and devoted to its chosen person, often wary of strangers and other animals.",
         requirementsSummary="Tiny and fragile around young kids or rough play; gets cold easily and often needs a sweater in cool weather."),
    dict(id="pug", species="dog", name="Pug", size="small",
         energyLevel=2, exerciseNeedsMinutesPerDay=25, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=2, sheddingLevel=4, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[12, 15], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["brachycephalic airway syndrome", "obesity", "eye injuries"],
         likesToDo=["short walks", "napping", "clowning around", "snacking"],
         personalitySummary="Comical, affectionate, and food-motivated, a natural entertainer that thrives on attention.",
         requirementsSummary="Sheds more than its short coat suggests; needs cool environments and portion control to avoid weight-related breathing issues."),
    dict(id="english-bulldog", species="dog", name="Bulldog (English)", size="medium",
         energyLevel=1, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=5, experienceLevelNeeded="beginner",
         lifespanYears=[8, 10], typicalCostTier="high", climatePreference="temperate",
         commonHealthIssues=["brachycephalic airway syndrome", "skin fold infections", "hip dysplasia"],
         likesToDo=["napping", "short strolls", "lounging with family", "chewing toys"],
         personalitySummary="Laid-back, dignified, and affectionate, content to spend most of the day near its people.",
         requirementsSummary="Very heat-sensitive and prone to breathing difficulty; skin folds need regular cleaning; often carries higher lifetime vet costs."),
    dict(id="australian-shepherd", species="dog", name="Australian Shepherd", size="medium",
         energyLevel=5, exerciseNeedsMinutesPerDay=90, goodWithKids=True, goodWithOtherPets=True,
         trainability=5, groomingNeeds=3, sheddingLevel=4, hypoallergenic=False, noiseLevel=3,
         goodForApartment=False, toleratesAloneTimeHours=3, experienceLevelNeeded="intermediate",
         lifespanYears=[12, 15], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hip dysplasia", "epilepsy", "eye disorders"],
         likesToDo=["herding games", "agility", "hiking", "advanced trick training"],
         personalitySummary="Smart, energetic, and work-driven, deeply bonded to its family and eager for a task.",
         requirementsSummary="Needs vigorous daily exercise and mental work; can develop herding-nipping habits without an outlet; thick coat sheds seasonally."),
    dict(id="great-dane", species="dog", name="Great Dane", size="large",
         energyLevel=3, exerciseNeedsMinutesPerDay=45, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=1, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="intermediate",
         lifespanYears=[8, 10], typicalCostTier="high", climatePreference="temperate",
         commonHealthIssues=["bloat", "cardiomyopathy", "hip dysplasia"],
         likesToDo=["gentle walks", "lounging", "leaning on people", "backyard play"],
         personalitySummary="A gentle giant — calm, affectionate, and surprisingly low-energy indoors despite its size.",
         requirementsSummary="Needs space and sturdy furniture; food and vet costs run high; short lifespan is an emotional consideration."),
    dict(id="boston-terrier", species="dog", name="Boston Terrier", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[11, 13], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["brachycephalic airway syndrome", "eye injuries", "allergies"],
         likesToDo=["short walks", "fetch", "playing with people", "napping in sunbeams"],
         personalitySummary="Friendly, lively, and easygoing, nicknamed the 'American Gentleman' for its good manners.",
         requirementsSummary="Moderate heat sensitivity from a shortened muzzle; low grooming needs; does well in smaller homes."),
    dict(id="basset-hound", species="dog", name="Basset Hound", size="medium",
         energyLevel=2, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=4,
         goodForApartment=True, toleratesAloneTimeHours=4, experienceLevelNeeded="beginner",
         lifespanYears=[12, 13], typicalCostTier="low", climatePreference="any",
         commonHealthIssues=["ear infections", "obesity", "back problems"],
         likesToDo=["sniffing walks", "napping", "scent games", "lounging with family"],
         personalitySummary="Laid-back, affectionate, and famously stubborn, with a deep bay and a nose that leads the way.",
         requirementsSummary="Long ears need regular cleaning to prevent infection; prone to weight gain from its low exercise drive; training takes patience."),

    # ---------------- CATS (15) ----------------
    dict(id="domestic-shorthair", species="cat", name="Domestic Shorthair", size="medium",
         energyLevel=3, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=1, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=10, experienceLevelNeeded="beginner",
         lifespanYears=[13, 17], typicalCostTier="low", climatePreference="any",
         commonHealthIssues=["obesity", "dental disease", "generally hardy"],
         likesToDo=["window watching", "toy play", "napping", "climbing cat trees"],
         personalitySummary="Wide-ranging personality since it's a mixed background, but generally adaptable, affectionate, and low-drama.",
         requirementsSummary="Minimal grooming and generally robust health; benefits from scratching posts and some interactive play daily."),
    dict(id="maine-coon", species="cat", name="Maine Coon", size="large",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=3, sheddingLevel=4, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=9, experienceLevelNeeded="beginner",
         lifespanYears=[12, 15], typicalCostTier="medium", climatePreference="cold",
         commonHealthIssues=["hypertrophic cardiomyopathy", "hip dysplasia", "spinal muscular atrophy"],
         likesToDo=["fetch", "climbing", "water play", "following people around the house"],
         personalitySummary="Gentle giants of the cat world — sociable, dog-like in loyalty, and famously good with families.",
         requirementsSummary="Long coat needs weekly brushing; large size means proportionally larger food and litter costs."),
    dict(id="siamese", species="cat", name="Siamese", size="medium",
         energyLevel=4, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=5,
         goodForApartment=True, toleratesAloneTimeHours=6, experienceLevelNeeded="intermediate",
         lifespanYears=[12, 15], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["dental disease", "respiratory issues", "progressive retinal atrophy"],
         likesToDo=["interactive toys", "puzzle feeders", "'talking' to owners", "perching up high"],
         personalitySummary="Vocal, social, and highly intelligent, often described as more dog-like in how closely it bonds.",
         requirementsSummary="Very people-oriented and can be vocal/demanding about attention; not a cat that thrives being left alone often."),
    dict(id="persian", species="cat", name="Persian", size="medium",
         energyLevel=1, exerciseNeedsMinutesPerDay=15, goodWithKids=True, goodWithOtherPets=True,
         trainability=1, groomingNeeds=5, sheddingLevel=4, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="intermediate",
         lifespanYears=[12, 17], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["polycystic kidney disease", "brachycephalic breathing issues", "tear duct overflow"],
         likesToDo=["quiet lounging", "gentle petting sessions", "napping in cozy spots"],
         personalitySummary="Calm, sweet, and dignified, happiest in a quiet, predictable home.",
         requirementsSummary="Long coat mats easily and needs daily brushing, often professional grooming; flat face can cause breathing and eye issues."),
    dict(id="ragdoll", species="cat", name="Ragdoll", size="large",
         energyLevel=2, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=3, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[12, 17], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hypertrophic cardiomyopathy", "obesity", "bladder stones"],
         likesToDo=["being carried around", "lap time", "gentle play", "greeting people at the door"],
         personalitySummary="Famously docile and affectionate, known for going limp with contentment when held.",
         requirementsSummary="Indoor-only recommended due to its trusting nature; semi-long coat needs weekly brushing."),
    dict(id="british-shorthair", species="cat", name="British Shorthair", size="medium",
         energyLevel=2, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=9, experienceLevelNeeded="beginner",
         lifespanYears=[12, 17], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hypertrophic cardiomyopathy", "obesity", "polycystic kidney disease"],
         likesToDo=["independent play", "napping", "quiet companionship", "window watching"],
         personalitySummary="Easygoing and undemanding, affectionate on its own terms rather than a constant lap cat.",
         requirementsSummary="Tolerates alone time well; prone to weight gain so portion control matters; dense coat needs weekly brushing."),
    dict(id="sphynx", species="cat", name="Sphynx", size="medium",
         energyLevel=4, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=4, sheddingLevel=1, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=6, experienceLevelNeeded="intermediate",
         lifespanYears=[9, 15], typicalCostTier="high", climatePreference="warm",
         commonHealthIssues=["hypertrophic cardiomyopathy", "skin conditions", "temperature sensitivity"],
         likesToDo=["climbing", "attention-seeking antics", "sunbathing", "curling up under blankets"],
         personalitySummary="Extroverted, mischievous, and people-obsessed, often described as more like a dog than a cat.",
         requirementsSummary="Hairless skin needs regular bathing and sun/cold protection; often needs sweaters in cool homes; not truly hypoallergenic (skin oils still shed dander)."),
    dict(id="bengal", species="cat", name="Bengal", size="medium",
         energyLevel=5, exerciseNeedsMinutesPerDay=45, goodWithKids=True, goodWithOtherPets=False,
         trainability=4, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=4,
         goodForApartment=False, toleratesAloneTimeHours=5, experienceLevelNeeded="experienced",
         lifespanYears=[12, 16], typicalCostTier="high", climatePreference="any",
         commonHealthIssues=["hypertrophic cardiomyopathy", "progressive retinal atrophy", "patellar luxation"],
         likesToDo=["climbing", "water play", "puzzle feeders", "leash walking"],
         personalitySummary="Athletic, bold, and endlessly curious, with a wild-cat look and a high-drive personality to match.",
         requirementsSummary="Needs significant daily enrichment and vertical space or it gets destructive; not ideal for a quiet, low-activity household."),
    dict(id="abyssinian", species="cat", name="Abyssinian", size="medium",
         energyLevel=5, exerciseNeedsMinutesPerDay=40, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=6, experienceLevelNeeded="intermediate",
         lifespanYears=[9, 15], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["progressive retinal atrophy", "gingivitis", "renal amyloidosis"],
         likesToDo=["climbing", "chasing toys", "exploring high perches", "interactive games"],
         personalitySummary="Energetic and inquisitive, always on the move and eager to investigate everything.",
         requirementsSummary="Needs daily play and vertical space to climb; gets bored (and mischievous) without enough stimulation."),
    dict(id="scottish-fold", species="cat", name="Scottish Fold", size="medium",
         energyLevel=2, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[11, 14], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["degenerative joint disease (cartilage)", "polycystic kidney disease", "ear infections"],
         likesToDo=["quiet play", "napping in unusual positions", "lap time"],
         personalitySummary="Sweet-natured and adaptable, known for its owl-like folded ears and calm demeanor.",
         requirementsSummary="The folded-ear trait is linked to a cartilage condition that needs monitoring; folded ears also need regular cleaning."),
    dict(id="russian-blue", species="cat", name="Russian Blue", size="medium",
         energyLevel=3, exerciseNeedsMinutesPerDay=25, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=2, sheddingLevel=2, hypoallergenic=True, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[15, 20], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["obesity", "bladder issues", "generally hardy"],
         likesToDo=["quiet play", "routine and predictability", "window watching"],
         personalitySummary="Gentle, reserved, and loyal to its people, often shy with strangers but deeply affectionate at home.",
         requirementsSummary="Produces less of the Fel d 1 allergen, making it a popular pick for mild allergy sufferers; prefers a calm, consistent routine."),
    dict(id="devon-rex", species="cat", name="Devon Rex", size="small",
         energyLevel=4, exerciseNeedsMinutesPerDay=35, goodWithKids=True, goodWithOtherPets=True,
         trainability=4, groomingNeeds=2, sheddingLevel=1, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=6, experienceLevelNeeded="intermediate",
         lifespanYears=[9, 15], typicalCostTier="medium", climatePreference="warm",
         commonHealthIssues=["hereditary myopathy", "skin sensitivity", "patellar luxation"],
         likesToDo=["climbing", "perching on shoulders", "playing fetch", "clownish antics"],
         personalitySummary="Playful, mischievous, and deeply attached to its people — sometimes called a 'pixie' cat for its elfin look and energy.",
         requirementsSummary="Fine curly coat provides less insulation, so it's sensitive to cold; skin needs occasional gentle cleaning."),
    dict(id="american-shorthair", species="cat", name="American Shorthair", size="medium",
         energyLevel=3, exerciseNeedsMinutesPerDay=25, goodWithKids=True, goodWithOtherPets=True,
         trainability=2, groomingNeeds=1, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=9, experienceLevelNeeded="beginner",
         lifespanYears=[15, 20], typicalCostTier="low", climatePreference="any",
         commonHealthIssues=["obesity", "hypertrophic cardiomyopathy", "generally hardy"],
         likesToDo=["toy play", "napping", "independent exploring"],
         personalitySummary="Easygoing, even-tempered, and low-maintenance, a sturdy all-around companion.",
         requirementsSummary="Very few special requirements beyond routine care; adapts well to most households and schedules."),
    dict(id="birman", species="cat", name="Birman", size="medium",
         energyLevel=2, exerciseNeedsMinutesPerDay=20, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=3, sheddingLevel=3, hypoallergenic=False, noiseLevel=2,
         goodForApartment=True, toleratesAloneTimeHours=7, experienceLevelNeeded="beginner",
         lifespanYears=[12, 16], typicalCostTier="medium", climatePreference="any",
         commonHealthIssues=["hypertrophic cardiomyopathy", "corneal dermoids", "kidney issues"],
         likesToDo=["gentle play", "following owners around", "lap time"],
         personalitySummary="Sweet, sociable, and gentle, known for striking blue eyes and quiet devotion to its family.",
         requirementsSummary="Semi-long coat sheds but doesn't mat as easily as a Persian's; enjoys company and does best without long stretches alone."),
    dict(id="norwegian-forest-cat", species="cat", name="Norwegian Forest Cat", size="large",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=True,
         trainability=3, groomingNeeds=3, sheddingLevel=4, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[14, 16], typicalCostTier="medium", climatePreference="cold",
         commonHealthIssues=["hypertrophic cardiomyopathy", "glycogen storage disease", "hip dysplasia"],
         likesToDo=["climbing", "cool-weather lounging", "independent exploring", "window watching"],
         personalitySummary="Independent but affectionate, a sturdy, weather-hardy breed with a calm, friendly streak.",
         requirementsSummary="Thick double coat sheds heavily in seasonal blowouts and needs weekly brushing; enjoys climbing so benefits from tall cat trees."),

    # ---------------- RABBITS (5) ----------------
    dict(id="holland-lop", species="rabbit", name="Holland Lop", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=3, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[7, 10], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["dental malocclusion", "GI stasis", "ear infections (from floppy ears)"],
         likesToDo=["supervised free-roam time", "chewing toys", "digging boxes", "being petted"],
         personalitySummary="Friendly and easygoing, one of the more sociable rabbit breeds and popular with first-time owners.",
         requirementsSummary="Needs a spacious pen plus daily out-of-cage exercise time; unlimited hay and a consistent diet are essential to prevent GI issues."),
    dict(id="mini-rex", species="rabbit", name="Mini Rex", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=3, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[5, 9], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["dental malocclusion", "sore hocks", "GI stasis"],
         likesToDo=["exploring", "plush-coat cuddling", "chew toys", "hopping around a rabbit-proofed room"],
         personalitySummary="Calm and velvety-soft (its coat is famously plush), generally gentle and easy to handle.",
         requirementsSummary="Short coat is low-maintenance but hard flooring can cause sore hocks — provide soft resting mats."),
    dict(id="netherland-dwarf", species="rabbit", name="Netherland Dwarf", size="small",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=False, goodWithOtherPets=False,
         trainability=2, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="intermediate",
         lifespanYears=[7, 10], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["dental malocclusion", "GI stasis", "skittishness-related injury"],
         likesToDo=["quick bursts of zoomies", "hiding spots", "chew toys", "watching from a safe distance"],
         personalitySummary="Small, energetic, and can be skittish — often better suited to calmer households and gentle, patient handling.",
         requirementsSummary="Tiny size makes it easily startled and fragile around boisterous kids; needs a secure, enriched enclosure with hideouts."),
    dict(id="flemish-giant", species="rabbit", name="Flemish Giant", size="large",
         energyLevel=2, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=4, groomingNeeds=2, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=False, toleratesAloneTimeHours=8, experienceLevelNeeded="intermediate",
         lifespanYears=[5, 8], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["sore hocks", "arthritis (due to size)", "obesity"],
         likesToDo=["lounging", "gentle petting sessions", "supervised room exploration"],
         personalitySummary="Docile and famously calm for a rabbit, often called a 'gentle giant' — can be very sweet with patient handling.",
         requirementsSummary="Needs a large enclosure well beyond standard hutch sizes and a bigger food budget than other rabbit breeds; heavy for kids to safely hold."),
    dict(id="lionhead-rabbit", species="rabbit", name="Lionhead", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=3, groomingNeeds=4, sheddingLevel=3, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[7, 9], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["wool block (from grooming/ingested fur)", "dental malocclusion", "GI stasis"],
         likesToDo=["exploring", "being brushed", "chew toys", "digging boxes"],
         personalitySummary="Playful and affectionate, known for its distinctive mane of fur around the head.",
         requirementsSummary="Mane needs regular brushing to prevent matting and wool block; otherwise a fairly easygoing companion breed."),

    # ---------------- SMALL RODENTS (5) ----------------
    dict(id="guinea-pig", species="rodent", name="Guinea Pig", size="medium",
         energyLevel=2, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=2, groomingNeeds=2, sheddingLevel=2, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=12, experienceLevelNeeded="beginner",
         lifespanYears=[5, 7], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["scurvy (vitamin C deficiency)", "dental overgrowth", "respiratory infections"],
         likesToDo=["floor time in a playpen", "chirping/wheeking at feeding time", "foraging for veggies", "companionship with other guinea pigs"],
         personalitySummary="Social and vocal, guinea pigs bond well with people and do best living with at least one same-species companion.",
         requirementsSummary="Needs a same-species friend (they're not solitary animals), a roomy cage, daily fresh vegetables, and a source of vitamin C."),
    dict(id="syrian-hamster", species="rodent", name="Syrian Hamster", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=30, goodWithKids=False, goodWithOtherPets=False,
         trainability=2, groomingNeeds=1, sheddingLevel=1, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=24, experienceLevelNeeded="beginner",
         lifespanYears=[2, 3], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["wet tail", "dental overgrowth", "obesity"],
         likesToDo=["running on a wheel", "burrowing", "solo nighttime exploring", "stuffing cheek pouches"],
         personalitySummary="Solitary and nocturnal — must be housed alone, most active at night, and generally low-interaction during the day.",
         requirementsSummary="Must live alone (Syrians are territorial); short lifespan is worth knowing upfront; needs a large wheel and deep bedding for burrowing."),
    dict(id="dwarf-hamster", species="rodent", name="Dwarf Hamster", size="small",
         energyLevel=4, exerciseNeedsMinutesPerDay=30, goodWithKids=False, goodWithOtherPets=False,
         trainability=2, groomingNeeds=1, sheddingLevel=1, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=24, experienceLevelNeeded="intermediate",
         lifespanYears=[1, 3], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["diabetes (in some lines)", "wet tail", "dental overgrowth"],
         likesToDo=["running on a wheel", "burrowing", "quick, darting exploration"],
         personalitySummary="Fast, small, and can be nippy — better watched than handled by younger kids, more of an observation pet.",
         requirementsSummary="Very fast and hard to hold securely; can sometimes live in same-sex pairs but often best alone; escape-proof housing is a must."),
    dict(id="gerbil", species="rodent", name="Gerbil", size="small",
         energyLevel=4, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=False,
         trainability=3, groomingNeeds=1, sheddingLevel=1, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=24, experienceLevelNeeded="beginner",
         lifespanYears=[2, 4], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["dental overgrowth", "tail slip injuries", "seizure susceptibility in some lines"],
         likesToDo=["digging deep tunnels", "chewing cardboard", "foraging", "socializing with cage-mates"],
         personalitySummary="Curious, active, and generally sociable in pairs or small groups of the same sex.",
         requirementsSummary="Needs deep bedding for natural digging behavior and a same-sex companion; low odor compared to other small rodents."),
    dict(id="fancy-rat", species="rodent", name="Fancy Rat", size="medium",
         energyLevel=3, exerciseNeedsMinutesPerDay=45, goodWithKids=True, goodWithOtherPets=False,
         trainability=5, groomingNeeds=1, sheddingLevel=2, hypoallergenic=False, noiseLevel=1,
         goodForApartment=True, toleratesAloneTimeHours=10, experienceLevelNeeded="beginner",
         lifespanYears=[2, 3], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["respiratory infections", "mammary tumors (unspayed females)", "obesity"],
         likesToDo=["trick training", "shoulder rides", "puzzle foraging", "playing with cage-mates"],
         personalitySummary="Highly intelligent and genuinely affectionate — often the most interactive and trainable of the small rodents.",
         requirementsSummary="Best kept in same-sex pairs or groups for social wellbeing; short lifespan; prone to respiratory issues in dusty bedding."),

    # ---------------- BIRDS (5) ----------------
    dict(id="budgerigar", species="bird", name="Budgerigar (Budgie)", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=4, groomingNeeds=2, sheddingLevel=2, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[5, 10], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["mites", "respiratory infections", "fatty liver disease"],
         likesToDo=["mimicking sounds/words", "mirror and toy play", "flying in a safe room", "chattering to cage-mates"],
         personalitySummary="Cheerful, social, and surprisingly good talkers for their size — a great entry point into bird ownership.",
         requirementsSummary="Needs daily out-of-cage flight time and social interaction; happier in pairs, though a single bird bonds closely with people."),
    dict(id="cockatiel", species="bird", name="Cockatiel", size="small",
         energyLevel=3, exerciseNeedsMinutesPerDay=60, goodWithKids=True, goodWithOtherPets=False,
         trainability=4, groomingNeeds=3, sheddingLevel=3, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=8, experienceLevelNeeded="beginner",
         lifespanYears=[15, 20], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["respiratory infections", "fatty liver disease", "feather picking (stress-related)"],
         likesToDo=["whistling tunes", "head scratches", "out-of-cage exploring", "mimicking household sounds"],
         personalitySummary="Affectionate and expressive, known for whistling and a crest that visibly signals its mood.",
         requirementsSummary="Long lifespan is a real commitment (often 15-20+ years); produces fine feather dust that can affect allergy sufferers; needs daily attention."),
    dict(id="canary", species="bird", name="Canary", size="small",
         energyLevel=2, exerciseNeedsMinutesPerDay=30, goodWithKids=True, goodWithOtherPets=False,
         trainability=1, groomingNeeds=1, sheddingLevel=1, hypoallergenic=False, noiseLevel=4,
         goodForApartment=True, toleratesAloneTimeHours=12, experienceLevelNeeded="beginner",
         lifespanYears=[10, 15], typicalCostTier="low", climatePreference="temperate",
         commonHealthIssues=["respiratory infections", "mites", "egg binding (females)"],
         likesToDo=["singing", "bathing", "hopping between perches", "watching its surroundings"],
         personalitySummary="A watch-don't-handle bird — prized for its song rather than interaction, generally not hand-tame.",
         requirementsSummary="Not meant to be held or cuddled; best for someone who wants birdsong and visual enjoyment over hands-on interaction; males sing more than females."),
    dict(id="green-cheeked-conure", species="bird", name="Green-cheeked Conure", size="small",
         energyLevel=4, exerciseNeedsMinutesPerDay=60, goodWithKids=False, goodWithOtherPets=False,
         trainability=4, groomingNeeds=2, sheddingLevel=2, hypoallergenic=False, noiseLevel=3,
         goodForApartment=True, toleratesAloneTimeHours=6, experienceLevelNeeded="intermediate",
         lifespanYears=[10, 15], typicalCostTier="medium", climatePreference="temperate",
         commonHealthIssues=["feather picking (stress-related)", "respiratory infections", "beak overgrowth"],
         likesToDo=["climbing on people", "chewing toys", "cuddling under a shirt collar", "learning tricks"],
         personalitySummary="Playful and cuddly with a big personality — comparatively quieter than larger parrots but still a real handful.",
         requirementsSummary="Can nip when startled, so supervised interaction with young kids is safer; needs daily out-of-cage time and chew-safe toys."),
    dict(id="african-grey-parrot", species="bird", name="African Grey Parrot", size="medium",
         energyLevel=4, exerciseNeedsMinutesPerDay=90, goodWithKids=False, goodWithOtherPets=False,
         trainability=5, groomingNeeds=3, sheddingLevel=3, hypoallergenic=False, noiseLevel=4,
         goodForApartment=False, toleratesAloneTimeHours=4, experienceLevelNeeded="experienced",
         lifespanYears=[40, 60], typicalCostTier="high", climatePreference="temperate",
         commonHealthIssues=["feather picking (stress-related)", "calcium deficiency", "psittacosis"],
         likesToDo=["problem-solving toys", "mimicking speech with real context", "socializing daily", "foraging games"],
         personalitySummary="Exceptionally intelligent — often compared to a young child cognitively — and deeply bonded but demanding of a companion.",
         requirementsSummary="Decades-long lifespan is a lifetime commitment across a household's changes; needs hours of daily mental engagement or develops stress behaviors like feather plucking; not a beginner bird."),
]

assert len(pets) == 50, f"expected 50 entries, got {len(pets)}"
by_species = {}
for p in pets:
    by_species[p["species"]] = by_species.get(p["species"], 0) + 1
print(by_species)

with open("data/pets.json", "w") as f:
    json.dump(pets, f, indent=2)
    f.write("\n")

print("wrote", len(pets), "entries to data/pets.json")
